version: "3"

services:
    db:
        image: "mysql:5.7"
        container_name: "desafio-nginx-node-db"
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks: 
            - desafio-nginx-node-back
    nginx:
        container_name: "desfio-nginx-node-nginx"  
        build: 
            context: ./nginx
        ports: 
            - 8080:80
        depends_on: 
            - db
    node-cli:
        container_name: "nodejs-cli"
        image: "node:16"
        volumes: 
            - ./node:/app
        working_dir: /app
        environment: 
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks: 
            - desafio-nginx-node-back
        depends_on: 
            - db
        profiles:
            - dev

networks: 
    desafio-nginx-node-back:
        driver: bridge
    desafio-nginx-node-front:
        driver: bridge
